const NONE = "./images/none.png"

// This is just a constant that checks if the game is over.
const FINISH = "FINISH";
const BITSYSCREEN = "BISTY";
const ZINESCREEN = "ZINE";

const NA = "<span aria-label='narrator'>● — ●</span>";
const BEADS = "Beads";
const FRECKLES = "Freckles";
let FLAVOR;

let DIALOGUE_CONTENT = [
    {
        id: 1,
        text: "You lay on your bed curled up in a blanket.",
        speakerName: NA,
        characterImg: NONE,
        next: 2,
    },
    {
        id: 2,
        text: "Loooooove…",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 3,
    },
    {
        id: 3,
        text: "…",
        speakerName: NA,
        characterImg: NONE,
        next: 4,
    },
    {
        id: 4,
        text: "LOOOOOOOOOOOOOOOOve-",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 5,
    },
    {
        id: 5,
        text: "I’m here! I’m here, you screaming goat.",
        speakerName: BEADS,
        characterImg: "n",
        next: 6,
    },
    {
        id: 6,
        text: "Your partner strides into the room whilst putting their coat on.",
        speakerName: NA,
        characterImg: NONE,
        next: 7,
    },
    {
        id: 7,
        text: "For someone with a sore throat, you sure are using it a lot.",
        speakerName: BEADS,
        characterImg: "n",
        next: 8,
    },
    {
        id: 8,
        text: "But I h<i>aaaa</i>ve to.",
        speakerName: FRECKLES,
        characterImg: "s",
        next: 9,
    },
    {
        id: 9,
        text: "You’re <i>leaving</i> me!",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 10,
    },
    {
        id: 10,
        text: "I’m just going to the store. We’re out of cold medicine.",
        speakerName: BEADS,
        characterImg: "n",
        next: 11,
    },
    {
        id: 11,
        text: "They grab their wallet and keys and shove them in their pockets.",
        speakerName: NA,
        characterImg: NONE,
        next: 12,
    },
    {
        id: 12,
        text: "I don’t <i>need</i> medicine. All I need is cuddles.",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 13,
    },
    {
        id: 13,
        text: "They let out a small chuckle.",
        speakerName: NA,
        characterImg: NONE,
        next: 14,
    },
    {
        id: 14,
        text: "Says the nasally sounding cutie with a fever.",
        speakerName: BEADS,
        characterImg: "s",
        next: 15,
    },
    {
        id: 15,
        text: "Hey! I’m not cute.",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 16,
    },
    {
      id: 16,
      characterImg: NONE,
      options: [
        {
          text: "“I’m adorable.”",
          nextText: 17,
          setState: { epilogue: 1 },
        },
        {
          text: "“I’m hot.”",
          nextText: 18,
          setState: { epilogue: 1 },
        },
        {
          text: "“You’re cute.”",
          nextText: 19,
          setState: { epilogue: 1 },
        }
      ],
    },
    {
        id: 17,
        text: "Heh. Yes, you are. No denying that.",
        speakerName: BEADS,
        characterImg: "s",
        next: 20,
    },
    {
        id: 18,
        text: "Literally, that’s why I’m buying you meds, hot stuff.",
        speakerName: BEADS,
        characterImg: "s",
        next: 20,
    },
    {
        id: 19,
        text: "Nothing's cuter than a cutie denying their cuteness.",
        speakerName: BEADS,
        characterImg: "s",
        next: 20,
    },
    {
        id: 20,
        text: "Hmpf!",
        speakerName: FRECKLES,
        characterImg: "n_b",
        next: 21,
    },
    {
        id: 21,
        text: "Your love walks to where you’re resting and bends down.",
        speakerName: NA,
        characterImg: NONE,
        next: 22,
    },
    {
        id: 22,
        text: "Aw, calm down now, my prickly pear.",
        speakerName: BEADS,
        characterImg: 's',
        next: 23,
    },
    {
        id: 23,
        text: "You can’t sweet talk your way outta this cruel endeavor.",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 24,
    },
    {
        id: 24,
        text: "Yet again, they let out that chuckle that warms your heart.",
        speakerName: NA,
        characterImg: NONE,
        next: 25,
    },
    {
        id: 25,
        text: "<i>Suffer</i>. <3",
        speakerName: BEADS,
        characterImg: "s",
        next: 26,
    },
    {
        id: 26,
        text: "They place a gentle kiss upon your temple before moving towards the door.",
        speakerName: NA,
        characterImg: NONE,
        next: 27,
    },
    {
        id: 27,
        text: "I’ll be back soon; don’t worry. I wouldn’t leave my wary puppy sick at home for long.",
        speakerName: BEADS,
        characterImg: "s",
        next: 28,
    },
    {
      id: 28,
      characterImg: "NONE",
      options: [
        {
          text: "“You’re wary puppy is saddened by your actions.”",
          nextText: 29,
        },
        {
          text: "“You’re gonna give your poor puppy separation anxiety.”",
          nextText: 30,
        },
        {
          text: "“I’ll bark at you.”",
          nextText: 31,
        }
      ],
    },
    {
        id: 29,
        text: "Aww, would belly rubs make you happier? Head pats? How about some ear scritches?",
        speakerName: BEADS,
        characterImg: "s",
        next: 32,
    },
    {
        id: 30,
        text: "Like my puppy doesn’t already have it.",
        speakerName: BEADS,
        characterImg: "s",
        next: 32,
    },
    {
        id: 31,
        text: "Leave that for the bedroom, doll.",
        speakerName: BEADS,
        characterImg: "s",
        next: 32,
    },
    {
        id: 32,
        text: "Aaa, just leave already. ",
        speakerName: FRECKLES,
        characterImg: "n_b",
        next: 33,
    },
    {
        id: 33,
        text: "Alright. I won’t be long, love. I’ll try to make it quick.",
        speakerName: BEADS,
        characterImg: "s",
        next: 34,
    },
    {
        id: 34,
        text: "Byyeee! I love you!",
        speakerName: BEADS,
        characterImg: "s",
        next: 35,
    },
    {
        id: 35,
        text: "They begin heading out the door.",
        speakerName: NA,
        characterImg: NONE,
        next: 36,
    },
    {
      id: 36,
      characterImg: "NONE",
      options: [
        {
          text: "“I LOVE YOU TOO!”",
          nextText: 38,
        },
        {
          text: "“I LOVE YOU MORE!”",
          nextText: 37,
        }
      ],
    },
    {
        id: 37,
        text: "Whatever you say, dear.",
        speakerName: BEADS,
        characterImg: "s",
        next: 38,
    },
    {
        id: 38,
        text: "They give you a small wave before shutting the door behind them.",
        speakerName: NA,
        characterImg: NONE,
        next: 39,
    },
    {
        id: 39,
        text: "…",
        speakerName: NA,
        characterImg: NONE,
        next: 40,
    },
    {
        id: 40,
        text: "Welp.",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 41,
    },
    {
        id: 41,
        text: "Looks like it’s just you now.",
        speakerName: NA,
        characterImg: NONE,
        next: 42,
    },
    {
        id: 42,
        text: "What to do. What to do.",
        speakerName: NA,
        characterImg: NONE,
        next: 43,
    },
    {
        id: 43,
        text: "You let your eyes search the room for possible ways of entertainment.",
        speakerName: NA,
        characterImg: NONE,
        next: 44,
    },
    {
        id: 44,
        text: "You spot the TV remote sitting on the nightstand on the <i>opposite</i> side of the bed.",
        speakerName: NA,
        characterImg: NONE,
        next: 45,
    },
    {
        id: 45,
        text: "Too far, not moving.",
        speakerName: NA,
        characterImg: NONE,
        next: 46,
    },
    {
        id: 46,
        text: "You look over to the nightstand on your side. There, your phone lies charging.",
        speakerName: NA,
        characterImg: NONE,
        next: 47,
    },
    {
        id: 47,
        text: "Only on 12%. You probably shouldn’t mess with it.",
        speakerName: NA,
        characterImg: NONE,
        next: 48,
    },
    {
        id: 48,
        text: "<i>yawwwwwwwwwwwn</i>",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 49,
    },
    {
        id: 49,
        text: "Tired.",
        speakerName: NA,
        characterImg: NONE,
        next: 50,
    },
    {
        id: 50,
        text: "Next to your phone lays a mini-comic zine you’ve read over almost a hundred times by now.",
        speakerName: NA,
        characterImg: NONE,
        next: 51,
    },
    {
        id: 51,
        text: "Might as well read it again. You always loved looking at the art.",
        speakerName: NA,
        characterImg: NONE,
        next: ZINESCREEN,
    },
    {
        id: 52,
        text: "<i>*Yaaawwwwwwn*</i>",
        speakerName: NA,
        characterImg: NONE,
        next: 53,
    },
    {
        id: 53,
        text: "You can’t help but let out a cough, making your already sore throat feels raw.",
        speakerName: NA,
        characterImg: NONE,
        next: 54,
    },
    {
        id: 54,
        text: "Man, why did reading always make you so tired?",
        speakerName: NA,
        characterImg: NONE,
        next: 55,
    },
    {
      id: 55,
      characterImg: "NONE",
      options: [
        {
          text: "Attempt to fight it off and fail.",
          nextText: 56,
        },
        {
          text: "Slip into your fever-driven oblivion.",
          nextText: 57,
        }
      ],
    },
    {
        id: 56,
        text: "You make a weak attempt to keep your increasingly heavy eyelids from closing but to no avail.",
        speakerName: NA,
        characterImg: NONE,
        next: 57,
    },
    {
        id: 57,
        text: "Fighting off your exhaustion was always a fruitless battle.",
        speakerName: NA,
        characterImg: NONE,
        next: 58,
    },
    {
        id: 58,
        text: "You embrace the warmth of your eyelids as your world fades to darkness.",
        speakerName: NA,
        characterImg: NONE,
        next: 59,
    },
    {
        id: 59,
        text: "You melt into your mind.",
        speakerName: NA,
        characterImg: NONE,
        next: BITSYSCREEN,
    },
    {
        id: 60,
        text: "You feel a gentle shake against your shoulder.",
        speakerName: NA,
        characterImg: NONE,
        next: 61,
    },
    {
        id: 61,
        text: "You groan as you open your eyes to the blinding light.",
        speakerName: NA,
        characterImg: NONE,
        next: 62,
    },
    {
        id: 62,
        text: "The sweet scent from your dream still lingers in your nostrils.",
        speakerName: NA,
        characterImg: NONE,
        next: 63,
    },
    {
        id: 63,
        text: "Wakey wakey, sleeping beauty.",
        speakerName: BEADS,
        characterImg: "s",
        next: 64,
    },
    {
        id: 64,
        text: "I got your medication <i>and</i> a surprise.",
        speakerName: BEADS,
        characterImg: "s",
        next: 65,
    },
    {
        id: 65,
        text: "What’s the surprise?",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 66,
    },
    {
        id: 66,
        text: "Holding in a grogy yawn, you readjust yourself enough to see that they’re holding something behind their back.",
        speakerName: NA,
        characterImg: NONE,
        next: 67,
    },
    {
        id: 67,
        text: "Can’t tell you. It’s a surprise.",
        speakerName: BEADS,
        characterImg: "s",
        next: 68,
    },
    {
        id: 68,
        text: "May I have I then?",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 69,
    },
    {
        id: 69,
        text: "You catch a glimpse of mischief in their eyes as they part their lips.",
        speakerName: NA,
        characterImg: NONE,
        next: 70,
    },
    {
        id: 70,
        text: "I dunno. That all depends on how good you've been lately.",
        speakerName: BEADS,
        characterImg: "s_b",
        next: 71,
    },
    {
        id: 71,
        text: "You squint at them as they smirk back at you.",
        speakerName: NA,
        characterImg: NONE,
        next: 72,
    },
    {
      id: 72,
      characterImg: "NONE",
      options: [
        {
          text: "“Obviously, I’m always on my bestest of behavior.”",
          nextText: 73,
        },
        {
          text: "“Let’s pretend like I have.”",
          nextText: 74,
        },
        {
          text: "“I’ll bark at you.”",
          nextText: 75,
        }
      ],
    },
    {
        id: 73,
        text: "‘Bestest’ isn’t a word, love.",
        speakerName: BEADS,
        characterImg: "s_b",
        next: 76,
    },
    {
        id: 74,
        text: "Oh? So you’re saying you haven't? What a shame.",
        speakerName: BEADS,
        characterImg: "s_b",
        next: 76,
    },
    {
        id: 75,
        text: "I’ll bite.",
        speakerName: BEADS,
        characterImg: "s_b",
        next: 76,
    },
    {
        id: 76,
        text: "<i>Come oooooon.</i>",
        speakerName: FRECKLES,
        characterImg: "s_b",
        next: 77,
    },
    {
        id: 77,
        text: "I’m sick. Pity me.",
        speakerName: FRECKLES,
        characterImg: "n_b",
        next: 78,
    },
    {
        id: 78,
        text: "<i>Mhmm.</i>",
        speakerName: BEADS,
        characterImg: "s_b",
        next: 79,
    },
    {
        id: 79,
        text: "It’s puppy dog eyes time.",
        speakerName: NA,
        characterImg: NONE,
        next: 80,
    },
    {
        id: 80,
        text: "Please. 🥺",
        speakerName: FRECKLES,
        characterImg: "n_b",
        next: 81,
    },
    {
        id: 81,
        text: "Their chuckle sends flutters through your body.",
        speakerName: NA,
        characterImg: NONE,
        next: 82,
    },
    {
        id: 82,
        text: "Fine. Fine.",
        speakerName: BEADS,
        characterImg: "s_b",
        next: 83,
    },
    {
        id: 83,
        text: "You’re lucky you’re cute.",
        speakerName: BEADS,
        characterImg: "s_b",
        next: 84,
    },
    {
        id: 84,
        text: "They pull a paper bag and cup away from behind their back.",
        speakerName: NA,
        characterImg: NONE,
        next: 85,
    },
    {
        id: 85,
        text: "Wait, that smell.",
        speakerName: NA,
        characterImg: NONE,
        next: 86,
    },
    {
        id: 86,
        text: "I decided to stop by the coffee shop on my way home.",
        speakerName: BEADS,
        characterImg: "s",
        next: 87,
    },
    {
        id: 87,
        text: "They hand you the freezing cup. Condensation wets your hand.",
        speakerName: NA,
        characterImg: NONE,
        next: 88,
    },
    {
        id: 88,
        text: "I got you your favorites: an iced latte and-",
        speakerName: BEADS,
        characterImg: "s",
        next: 89,
    },
    {
        id: 89,
        text: "They open the bag and tilt it so you can see the inside.",
        speakerName: NA,
        characterImg: NONE,
        next: 90,
    },
    {
        id: 90,
        text: "Some fresh cinnamon rolls.",
        speakerName: BEADS,
        characterImg: "s",
        next: 91,
    },
    {
        id: 91,
        text: "I figured I’d get some sweets for my sweetie.",
        speakerName: BEADS,
        characterImg: "s",
        next: 92,
    },
    {
      id: 92,
      characterImg: "NONE",
      options: [
        {
          text: "“dwefgfghfjhgdfhgjftydhrtegrsbdnytrtgrt” <3",
          nextText: 93,
        },
        {
          text: "“Thank you so much! I love you! I love you!”",
          nextText: 93,
        },
        {
          text: "*take big slurp* <3<3<3",
          nextText: 93,
        }
      ],
    },
    {
        id: 93,
        text: "I love you too, my contaminated lover.",
        speakerName: BEADS,
        characterImg: "s",
        next: 94,
    },
    {
        id: 94,
        text: "Don’t forget, though, you still gotta take your medication.",
        speakerName: BEADS,
        characterImg: "s",
        next: 95,
    },
    {
        id: 95,
        text: "No, gross.",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 96,
    },
    {
        id: 96,
        text: "It’s cherry.",
        speakerName: BEADS,
        characterImg: "s",
        next: 97,
    },
    {
        id: 97,
        text: "That’s even <i>worse</i>.",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 98,
    },
    {
        id: 98,
        text: "Yep, but now you have treats that I was so <i>generous</i> to get you, to wash the taste out of your mouth.",
        speakerName: BEADS,
        characterImg: "s",
        next: 99,
    },
    {
        id: 99,
        text: "Ugh, I suppose.",
        speakerName: FRECKLES,
        characterImg: "n",
        next: 100,
    },
    {
        id: 100,
        text: "Your generosity has saved me from living in utter despair. Thank you.",
        speakerName: FRECKLES,
        characterImg: "s",
        next: 101,
    },
    {
        id: 101,
        text: "You’re very welcome.",
        speakerName: BEADS,
        characterImg: "s_b",
        next: 102,
    },
    {
        id: 102,
        text: "You lean forward to kiss them, but they back away.",
        speakerName: NA,
        characterImg: NONE,
        next: 103,
    },
    {
        id: 103,
        text: "Nuh uh uh, sicko.",
        speakerName: BEADS,
        characterImg: "s",
        next: 104,
    },
    {
        id: 104,
        text: "Awww, but I let you kiss me when you’re sick.",
        speakerName: FRECKLES,
        characterImg: "s",
        next: 105,
    },
    {
        id: 105,
        text: "That’s because you have no sense of self-preservation.",
        speakerName: BEADS,
        characterImg: "s",
        next: 106,
    },
    {
        id: 106,
        text: "They grab your chin and kiss you on the cheek.",
        speakerName: NA,
        characterImg: NONE,
        next: 107,
    },
    {
        id: 107,
        text: "I’d personally like to stay healthy.",
        speakerName: BEADS,
        characterImg: "s",
        next: 108,
    },
    {
        id: 108,
        text: "<i>Fiiiiine</i>, but I expect cuddles.",
        speakerName: FRECKLES,
        characterImg: "s",
        next: 109,
    },
    {
        id: 109,
        text: "Of course.",
        speakerName: BEADS,
        characterImg: "s",
        next: FINISH,
    },
];

const EPILOGUES = [
  {
    id: 1,
    text: "You spend the rest of the night eating delicious treats, cuddling, and finally getting to watch TV (your partner graciously got the remote for you).",
  }
];
